### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_warmup_lr'

### ISSUE THREAD

**Issue by fhaji75** [ming71/Rotated-RetinaNet#13]
when installing packages of requirements I got this error : 
ERROR: Could not find a version that satisfies the requirement torch_warmup_lr (from versions: none)
ERROR: No matching distribution found for torch_warmup_lr
and if I didn't install them I got error "ModuleNotFoundError: No module named 'torch_warmup_lr'"

**Comment by ming71** [comment]
pip install git+git://github.com/lehduong/torch-warmup-lr.git
