### ISSUE TITLE
缺少文件 'polyiou.i'

### ISSUE THREAD

**Issue by bjmwang** [ming71/Rotated-RetinaNet#3]
Unable to find file 'polyiou.i', while installing DotaDevKit:
```
sudo apt-get install swig
swig -c++ -python polyiou.i # here!
python setup.py build_ext --inplace
```

应该怎样做, 直接从[官方](https://github.com/CAPTAIN-WHU/DOTA_devkit)取吗?

**Comment by bjmwang** [comment]
fixed by:

1. clone https://github.com/CAPTAIN-WHU/DOTA_devkit
2. run the script
```
swig -c++ -python polyiou.i # supposed swig has been installed
python setup.py build_ext --inplace
```
3. copy the generated `.so` to the project root.

Thx

**Comment by ming71** [comment]
No need to run that script, just execute:
```
cd datasets/DOTA_devkit
swig -c++ -python polyiou.i # supposed swig has been installed
python setup.py build_ext --inplace
```
