### ISSUE TITLE
代码迁移的问题

### ISSUE THREAD

**Issue by yzk-lab** [ming71/Rotated-RetinaNet#4]
作者，你好，请问你这个旋转主要是体现在代码的哪个部分？如果我需要进行旋转部分的代码同其他模块结合，我应该怎么处理？希望你能给我一点建议，谢谢你。

**Comment by ming71** [comment]
就是在原来的$x,y,w,h$之外简单的加了个角度回归，没有别的任何trick。核心修改的部分在model.py, bbox.py,
