### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by gengyanlei** [ming71/Rotated-RetinaNet#5]
![image](https://user-images.githubusercontent.com/22360785/103520848-c6b79f80-4eb2-11eb-8d28-033f54cdbd73.png)

你好，我从你提供的UCAS-AOD-benchmark仓库下载的模型，按照你的步骤，运行demo.py出错，有些代码细节没有明白，不知道怎么修改

**Comment by gengyanlei** [comment]
anchor设置问题

**Comment by ming71** [comment]
模型要与设置匹配，代码是没有问题的

**Comment by gengyanlei** [comment]
![image](https://user-images.githubusercontent.com/22360785/108796165-0fdac480-75c3-11eb-88a3-541b6556a62d.png)

你的代码确实有好多小细节需要注意啊，好多匹配不上的。测试时权重参数；你的anchor是3*5=15，但是权重是9，因此我修改了。

**Comment by ming71** [comment]
> 实有好多小细节需要注意啊，好多匹配不上的。测试时权重参数；你的anchor是3*5=15，但是权重是9，因此我

这个代码其实非常简单，一点都不复杂，你不用我训练好的权重自己跑不就行了.....
